### ISSUE TITLE
example does not run as expected

### ISSUE THREAD

**Issue by nulman** [aleneum/transitions-gui#6] opened 2019-01-06 14:20 UTC
the example starts the server ok and im able to get there with a browser(chrome) and even move things around, but if i try to click an edge i get an error on the python side:
```
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Lib\site-packages\tornado\websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Lib\site-packages\transitions_gui\handlers\__init__.py", line 37, in on_message
    self.machine.process_message(message)
  File "C:\WinPython-64bit-3.6.3.0Qt5\python-3.6.3.amd64\Lib\site-packages\transitions\core.py", line 1102, in __getattr__
    raise AttributeError("'{}' does not exist on <Machine@{}>".format(name, id(self)))
AttributeError: 'process_message' does not exist on <Machine@2978679876352>
```

**Comment by aleneum** [comment] 2019-01-07 11:02
Thank you for the report @nulman. Much appreciated. I could reproduce and fix the underlying issue. If the issue still occurs, comment here and I will reopen the issue if necessary.

**Comment by aleneum** [comment] 2019-01-09 13:53
Hello @nulman,

does your Python environment contain `nose`? Could you run `nosetests` in the `transitions-gui` project folder? Note that no other service (e.g. another instance of `WebMachine`) should run during the test. Otherwise port 8080 will be in use and all tests should fail.

I wonder why the issue still persists for you since `WebMachine` now has the required `process_message` method  which was previously falsely assigned to `WebTransition`. Did you maybe install `transitions-gui` into your environment? This could cause a wrong/older version of `WebMachine` to be used.

**Comment by aleneum** [comment] 2019-01-29 22:07
@nulman: Could you identify the cause of the `AttributeError`?

**Comment by aleneum** [comment] 2019-08-20 19:06
This issue went stale. I will close this issue. If it still persist, feel free to comment and I will reopen the issue if necessary.

**Closed by aleneum** 2019-08-20 19:06 UTC
Labels: bug
